language: node_js
node_js:
- 4
install:
- npm install
- npm install -g mocha
deploy:
  provider: npm
  on:
    tags: true
  api_key:
    secure: n+e0ja3J0uqjlSJ66yyHeSpnuHbyYU0QFOtt3TOx61h+7sgl/XAOFlXgMrWFhK5gIHdL3W2dxkEcc2tp9skEDdrdBnw4UUCu1Z+XXavS+58gA0weRidH80Q9WYorfPFSTiRCZ/d9AvGKbpmCli9c0ZURZcmt1xfKB8ruFFrak5QiFNBLo4cCqVMBHCcn7hA1+58ksF6108VYXBGa/saWPJuWoe1Gl3rqAE2RtKOtW7yZmc0auhdTqq4lO25Ch+IyoMKmrbqjBavYzHMvZnWVRjAQnfacnCi317z3BfPjLEb37cy5TjX40O9z7AUoazIi1NYZlcqMS8CIURJkODtvO7OZk+HCs5zjpgV3wSSoLXY6tqhWceCwAtNcfQEHgF8jle7q+azVbP/666XZp/V1Snllgvb2xkrJHvmPvPjPe36Wk0dkzFK1Eypdl8tTTmMeo34c9YXhmaNw54u7Xl2uVeTTcIdP8fqPxqaVrO41jgfuxpdP7707+Tv9OBHURXIrcLXJaQq3nIiKs/YODOXPKD/9RBpYqkX42ZGWZwRtU+yWfsZetUlmAEfKUOdNQnNSvd/KFrpOGLXcn8YkBwhmraQGxOTB/u7ObhHKvRUWHx9+nbjRfjzEH31hxmThqzVFJQrZsh4zDZAukExJ6/aWLqrXXF+/W775jq4lmoWt3HY=
  email:
    secure: Py7uaZLi/DbsrN3FpP6K0rvrCn4QRdgqV0hjA1QMRuNt+uKz0szTtI43dwpM2FlfSD3c0CaLWlDgsmR7fzL6OU/ytCuZtrEE3MCTTkJnyp5GLTu8wr3Mwzq5TUOuuq7fGXMhH9aq5J/YIMEwMhJB+N6+re4f9dIL1tvxaHp7Nt6mKHASebWcJXKDbdHo0H9t//JJHa+10b/TMtvXV0w9Rs/tKMHiSE78sZZlfYaIatjce3hrvH2u1s+p22CBT9Ahh39s94NySVXM6QpL/qdtA6AJk5qUwGxRy3HpN+1px31x09HScbsSdOIGbOgc2zIhoKcSi4wwGlVecMghq+6TKcMMG3KWH8W6tadavV1Zyv11uWkN+GvOerYuXGDVrOxY5oY9rI68Wt9VBQeIJyMKpJBOD/FHYHdSL2ShNB1IR4c9naT3GRiDP2d/JwfJeoLAz2lIf54hsk8805g3TNC4wKC4Ir4g/xarLyqmW/3eBwrlW4klvzHbp+wpvX7YIExz8bCMK3eHBLIHXCS+P2v6HDVFAFH9sbdDCHDpFp0nomXSBi9c8aDfC/s6yWDA4LARuduAq+W6iE82qC1j0c1kIiL1qlHJFOsfFg9a/+atln5UmXEesMU/FJJh6h2l3Vwgkk2BKrivuDpmH2L3ljeq/0G/cE7//+MTijfKnjm0YF0=
